# Generated by Django 3.2.3 on 2023-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=200, verbose_name='Единица измерения'),
        ),
    ]
