# Generated by Django 3.2.3 on 2023-08-07 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_auto_20230804_1234"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
