# Generated by Django 3.2.3 on 2023-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'гость'), ('authorized', 'авторизованный'), ('admin', 'админ')], default='anon', max_length=20, verbose_name='Статус пользователя в системе'),
        ),
    ]
